### PR TITLE
Use zig lib instead of zig ar for msvc targets

### LINKED ISSUE #313: `ar: error: unknown option :` while building `stacker@0.1.17` or `psm v0.1.24`
Occurs on both github actions and local builds.

```
warning: psm@0.1.24: ar: error: unknown option :
error: failed to run custom build command for `psm v0.1.24`

Caused by:
  process didn't exit successfully: `D:\a\rimeka\rimeka\target\release\build\psm-88de7bb624b0f434\build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some(3)
  OUT_DIR = Some(D:\a\rimeka\rimeka\target\x86_64-pc-windows-msvc\release\build\psm-7ea5c06c7ad6e777\out)
  TARGET = Some(x86_64-pc-windows-msvc)
  cargo:rerun-if-env-changed=VCINSTALLDIR
  VCINSTALLDIR = None
  cargo:rerun-if-env-changed=VSTEL_MSBuildProjectFullPath
  VSTEL_MSBuildProjectFullPath = None
  cargo:rerun-if-env-changed=VSCMD_ARG_VCVARS_SPECTRE
  VSCMD_ARG_VCVARS_SPECTRE = None
  cargo:rerun-if-env-changed=WindowsSdkDir
  WindowsSdkDir = None
  cargo:rerun-if-env-changed=WindowsSDKVersion
  WindowsSDKVersion = None
  cargo:rerun-if-env-changed=LIB
  LIB = None
  PATH = Some(D:\a\rimeka\rimeka\target\release\deps;D:\a\rimeka\rimeka\target\release;C:\Users\runneradmin\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\x86_64-pc-windows-msvc\lib;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\runneradmin\bin;C:\hostedtoolcache\windows\zig\0.13.0\x64;C:\Program Files\MongoDB\Server\5.0\bin;C:\aliyun-cli;C:\vcpkg;C:\Program Files (x86)\NSIS\;C:\tools\zstd;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\3.3.1\x64;C:\cabal\bin;C:\\ghcup\bin;C:\mingw64\bin;C:\Program Files\dotnet;C:\Program Files\MySQL\MySQL Server 8.0\bin;C:\Program Files\R\R-4.4.2\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\SeleniumWebDrivers\EdgeDriver\;C:\SeleniumWebDrivers\ChromeDriver;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\npm\prefix;C:\hostedtoolcache\windows\go\1.21.13\x64\bin;C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts;C:\hostedtoolcache\windows\Python\3.9.13\x64;C:\hostedtoolcache\windows\Ruby\3.0.7\x64\bin;C:\Program Files\OpenSSL\bin;C:\tools\kotlinc\bin;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.442-6\x64\bin;C:\Program Files\ImageMagick-7.1.1-Q16-HDRI;C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\ProgramData\Chocolatey\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\WiX Toolset v3.14\bin;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\160\DTS\Binn\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.9.9\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI\;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\LLVM\bin;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\.cargo\bin;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps)
  cargo:rerun-if-env-changed=INCLUDE
  INCLUDE = None
  HOST = Some(x86_64-pc-windows-msvc)
  cargo:rerun-if-env-changed=CC_x86_64-pc-windows-msvc
  CC_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CC_x86_64_pc_windows_msvc
  CC_x86_64_pc_windows_msvc = Some(C:\Users\runneradmin\AppData\Local\cargo-zigbuild\0.19.7\zigcc-x86_64-pc-windows-msvc-4dad.bat)
  RUSTC_WRAPPER = None
  cargo:rerun-if-env-changed=CC_ENABLE_DEBUG_OUTPUT
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some(false)
  cargo:rerun-if-env-changed=CFLAGS_x86_64-pc-windows-msvc
  CFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_pc_windows_msvc
  CFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  CARGO_ENCODED_RUSTFLAGS = Some()
  cargo:rustc-check-cfg=cfg(switchable_stack,asm,link_asm)
  cargo:rustc-cfg=asm
  cargo:rustc-cfg=link_asm

  C:\Users\runneradmin\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\psm-0.1.24>"C:\Users\runneradmin\.cargo\bin\cargo-zigbuild.exe" zig cc -- -g -target x86_64-windows-msvc -O3 -ffunction-sections -fdata-sections -m64 "--target=x86_64-pc-windows-msvc" -Wall -Wextra -xassembler-with-cpp -DCFG_TARGET_OS_windows -DCFG_TARGET_ARCH_x86_64 -DCFG_TARGET_ENV_msvc -o D:\a\rimeka\rimeka\target\x86_64-pc-windows-msvc\release\build\psm-7ea5c06c7ad6e777\out\4f9a91766097c4c5-x86_64_windows_gnu.o -c src/arch/x86_64_windows_gnu.s 
  cargo:rerun-if-env-changed=AR_x86_64-pc-windows-msvc
  AR_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=AR_x86_64_pc_windows_msvc
  AR_x86_64_pc_windows_msvc = Some(C:\Users\runneradmin\AppData\Local\cargo-zigbuild\0.19.7\ar.exe)
  cargo:rerun-if-env-changed=ARFLAGS_x86_64-pc-windows-msvc
  ARFLAGS_x86_64-pc-windows-msvc = None
  cargo:rerun-if-env-changed=ARFLAGS_x86_64_pc_windows_msvc
  ARFLAGS_x86_64_pc_windows_msvc = None
  cargo:rerun-if-env-changed=HOST_ARFLAGS
  HOST_ARFLAGS = None
  cargo:rerun-if-env-changed=ARFLAGS
  ARFLAGS = None
  OVERVIEW: LLVM Archiver

  USAGE: ar [options] [-]<operation>[modifiers] [relpos] [count] <archive> [files]
         ar -M [<mri-script]

  OPTIONS:
    --format              - archive format to create
      =default            -   default
      =gnu                -   gnu
      =darwin             -   darwin
      =bsd                -   bsd
      =bigarchive         -   big archive (AIX OS)
    --plugin=<string>     - ignored for compatibility
    -h --help             - display this help and exit
    --output              - the directory to extract archive members to
    --rsp-quoting         - quoting style for response files
      =posix              -   posix
      =windows            -   windows
    --thin                - create a thin archive
    --version             - print the version and exit
    -X{32|64|32_64|any}   - object mode (only for AIX OS)
    @<file>               - read options from <file>

  OPERATIONS:
    d - delete [files] from the archive
    m - move [files] in the archive
    p - print contents of [files] found in the archive
    q - quick append [files] to the archive
    r - replace or insert [files] into the archive
    s - act as ranlib
    t - display list of files in archive
    x - extract [files] from the archive

  MODIFIERS:
    [a] - put [files] after [relpos]
    [b] - put [files] before [relpos] (same as [i])
    [c] - do not warn if archive had to be created
    [D] - use zero for timestamps and uids/gids (default)
    [h] - display this help and exit
    [i] - put [files] before [relpos] (same as [b])
    [l] - ignored for compatibility
    [L] - add archive's contents
    [N] - use instance [count] of name
    [o] - preserve original dates
    [O] - display member offsets
    [P] - use full names when matching (implied for thin archives)
    [s] - create an archive index (cf. ranlib)
    [S] - do not build a symbol table
    [T] - deprecated, use --thin instead
    [u] - update only [files] newer than archive contents
    [U] - use actual timestamps and uids/gids
    [v] - be verbose about actions taken
    [V] - display the version and exit
  cargo:warning=ar: error: unknown option :

  --- stderr


  error occurred in cc-rs: Command "C:\\Users\\runneradmin\\AppData\\Local\\cargo-zigbuild\\0.19.7\\ar.exe" "-out:D:\\a\\rimeka\\rimeka\\target\\x86_64-pc-windows-msvc\\release\\build\\psm-7ea5c06c7ad6e777\\out\\libpsm_s.a" "-nologo" "D:\\a\\rimeka\\rimeka\\target\\x86_64-pc-windows-msvc\\release\\build\\psm-7ea5c06c7ad6e777\\out\\4f9a91766097c4c5-x86_64_windows_gnu.o" with args C:\Users\runneradmin\AppData\Local\cargo-zigbuild\0.19.7\ar.exe did not execute successfully (status code exit code: 1).
```

### PR DESCRIPTION
**Pull request by balthild**
Fixes #313

### CODE REVIEW

File: src/zig.rs [hunk 1]
```diff
@@ -49,6 +49,13 @@ pub enum Zig {
         #[arg(num_args = 1.., trailing_var_arg = true)]
         args: Vec<String>,
     },
+    /// `zig lib` wrapper
+    #[command(name = "lib")]
+    Lib {
+        /// `zig ranlib` arguments
```
Comment (messense) [inline src/zig.rs:55]:
```suggestion
        /// `zig lib` arguments
```

**Review by messense — APPROVED** [review]
